-d H:\nestang\nestang-25k\impl\gwsynthesis\nes.vg
-p GW5A-25A-MBGA121N-1
-pn GW5A-LV25MG121NES
-cst H:\nestang\nestang-25k\src\nestang.cst
-cfg H:\nestang\nestang-25k\impl\pnr\device.cfg
-sdc H:\nestang\nestang-25k\src\nes.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
