`define CORE0_DEF_SIGNAL_IN_EN
`define CORE0_DEF_TRIG_0_EN
`define DYNAMIC_EXPRESSION_0
`define EXPRESSION_0_EN_0
`define CORE0_DEF_SYN_DYNAMIC_BSRAM
`define CORE0_DEF_SYN_BSRAM
`define FORCE_REG_CAPTURE_F_0
