-d F:\TangPrimer-25K-example\pmod_lcd\impl\gwsynthesis\pmod_lcd.vg
-p GW5A-25A-MBGA121N-1
-pn GW5A-LV25MG121NES
-cst F:\TangPrimer-25K-example\pmod_lcd\src\pmod_lcd.cst
-cfg F:\TangPrimer-25K-example\pmod_lcd\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-ireg_not_in_iob
-oreg_not_in_iob
-ioreg_not_in_iob
-cst_error
-correct_hold 1
-route_maxfan 23
