-d F:\TangPrimer-25K-example\UART\impl\gwsynthesis\uart_Hello.vg
-p GW5A-25A-MBGA121N-1
-pn GW5A-LV25MG121NES
-cst F:\TangPrimer-25K-example\UART\src\top.cst
-cfg F:\TangPrimer-25K-example\UART\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
